[tool.poetry]
name = "dangerzone"
version = "0.4.0"
description = "Take potentially dangerous PDFs, office documents, or images and convert them to safe PDFs"
authors = ["Micah Lee <micah.lee@theintercept.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
click = "*"
appdirs = "*"
PySide2 = {version = "5.15.2.1", platform = "linux"}
pyside6 = {version = "^6.4.1", markers = "sys_platform == 'win32' or sys_platform == 'darwin'"}
colorama = "*"
cx_freeze = {version = "^6.13.1", platform = "win32"}
pywin32 = {version = "*", platform = "win32"}
pyxdg = {version = "*", platform = "linux"}
pyinstaller = {version = "*", platform = "darwin"}
strip-ansi = {version = "*", platform = "darwin"}

[tool.poetry.scripts]
dangerzone = 'dangerzone:main'
dangerzone-container = 'dangerzone:main'
dangerzone-cli = 'dangerzone:main'

[tool.poetry.group.dev.dependencies]
setuptools = {version = "*", platform = "win32"}
strip-ansi = "*"

[tool.poetry.group.lint.dependencies]
black = "*"
isort = "*"
mypy = "*"
PySide2-stubs = "*"

[tool.poetry.group.test.dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.10.0"
pytest-xdist = "^2.5.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
