#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Load whisperzone module and resources from the source code tree
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.whisperzone_dev = True

import whisperzone

whisperzone.main()
